import { SECTIONS_CATEGORIES } from "@constant/components";

const SectionsList = [
    SECTIONS_CATEGORIES.NAVIGATION,
    SECTIONS_CATEGORIES.HERO,
    SECTIONS_CATEGORIES.FEATURES,
    SECTIONS_CATEGORIES.GALLERY,
    SECTIONS_CATEGORIES.POSTS,
    SECTIONS_CATEGORIES.TEAMS,
    SECTIONS_CATEGORIES.TESTINOMIALS,
    SECTIONS_CATEGORIES.FOOTER,
]

export default SectionsList;